### ISSUE TITLE
Remove mdadm if no MD array is needed

### ISSUE THREAD

**Issue by jkirk** [jkirk/ansible-role-base#1]
Should we add lines like these to remove mdadm if no MD array is in use?
```yaml
  - name: Check if /dev/md/0 exists
    stat: path=/dev/md/0
    register: md0
  - name: Remove mdadm if no MD array is needed
    apt: name=mdadm state=absent
    when: md0.stat.exists == False
```
Do we have software raid systems where we do not have `/dev/md0` (i.e. `/dev/md1` only)?
